# Generated by Django 5.2.2 on 2025-12-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_due', 'Task Due Soon'), ('task_completed', 'Task Completed')], max_length=50),
        ),
    ]
