# Generated by Django 5.2.9 on 2026-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_due', 'Task Due Soon'), ('task_completed', 'Task Completed'), ('admin_task_created', 'Admin Task Created'), ('admin_task_updated', 'Admin Task Updated'), ('manager_task_overdue', 'Manager Task Overdue'), ('admin_task_overdue', 'Admin Task Overdue')], max_length=50),
        ),
    ]
