# Generated by Django 5.2.9 on 2026-01-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_created_by_task_group_taskgroup_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
